import type {InfinizoomProject,RendererType,ZoomMode,ZoomNode} from "./schema.ts";
import {slugify} from "./lib/slug.ts";
const tail:ZoomNode[]=[
{id:"material",label:"Material microstructure",scaleM:1e-5,renderer:"material",parent:"component",children:["molecule"],visual:{density:1,motion:"subtle"}},
{id:"molecule",label:"Molecular structure",scaleM:1e-9,renderer:"molecule",parent:"material",children:["atom"],visual:{density:1,motion:"active"}},
{id:"atom",label:"Atom",scaleM:1e-10,renderer:"atom",parent:"molecule",children:["nucleus"],visual:{density:1,motion:"active"}},
{id:"nucleus",label:"Atomic nucleus",scaleM:5e-15,renderer:"nucleus",parent:"atom",children:["quark"],visual:{density:1,motion:"active"}},
{id:"quark",label:"Quark scale",scaleM:1e-18,renderer:"particle",parent:"nucleus",visual:{density:1,motion:"active"}}];
function infer(s0:string):{mode:ZoomMode;component:string;renderer:RendererType}{const s=s0.toLowerCase();if(/(github|repo|repository|code|software|app|website|protocol|blockchain|bitcoin|ethereum|fynch)/.test(s))return{mode:"hybrid",component:"Core system",renderer:"network"};if(/(screen|display|monitor|phone|iphone|ipad|tv)/.test(s))return{mode:"physical",component:"Display subsystem",renderer:"screen"};if(/(computer|macbook|laptop|chip|cpu|gpu|camera)/.test(s))return{mode:"physical",component:"Compute subsystem",renderer:"chip"};if(/(watch|engine|car|robot|machine|motor|bike)/.test(s))return{mode:"physical",component:"Mechanical assembly",renderer:"machine"};if(/(plant|animal|human|body|food|chicken|tender|cell|organ)/.test(s))return{mode:"physical",component:"Living or organic structure",renderer:"cell"};return{mode:"physical",component:"Meaningful internal component",renderer:"machine"}}
export function scaffoldProject(subject:string,prompt=subject):InfinizoomProject{const slug=slugify(subject),i=infer(subject);const nodes:ZoomNode[]=[{id:"context",label:`${subject} context`,scaleM:4,renderer:"room",children:["subject"],visual:{density:.7,motion:"subtle"}},{id:"subject",label:subject,scaleM:.25,renderer:"product",parent:"context",children:["component"],visual:{density:.9,motion:"active"}},{id:"component",label:i.component,scaleM:.02,renderer:i.renderer,parent:"subject",children:["material"],visual:{density:1,motion:"active"}},...tail];return{version:2,name:subject,slug,prompt,mode:i.mode,startNode:"context",defaultRoute:"main",durationSeconds:20,fidelity:"high",style:{background:"#050706",track:"#63ff9b",accent:"#f3f7f4",feel:["dense","alive","purposeful"]},authoring:{status:"scaffold",generatedAt:new Date().toISOString(),notes:["Fallback scaffold. Ask the INFINIZOOM skill to research and replace generic nodes for high-fidelity production."]},nodes,routes:[{id:"main",label:"Main route",nodes:nodes.map(n=>n.id)}]}}
